version: "3"

services:

  vehicle-server:
    container_name: vehicle-server
    image: ramesesinc/local-vehicle-server:255.01.003.002
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    env_file:
      - ./env.conf
      - ../../_res/env.conf
      - ../../_custom/env.conf
    ports: 
      - "8072:8070"
    volumes:
      - ../../_res/connections:/apps/enterprise/connections/ext
      - ../../_custom/datasources/vehicleds:/services/datasources/mainds

      - ../../_custom/module-server/vehicle:/apps/enterprise/modules/ext/zzz-module-server

      - ./server/system_modules:/services/modules
      - ./server/app_modules/rameses-gov-etracs-vehicle-services.jar:/apps/enterprise/modules/rameses-gov-etracs-vehicle-services.jar
