version: "3"

services:
  etracs-server:
    volumes:
      ## this is only a seed mapping, please do not remove
      ##
      - ../../_custom/.emptydir:/.emptydir

      ## mounted RPTIS build rptis-255.04.04
      - ./dev_modules/rptis-255.04.04/server:/services/modules/rptis
      - ./dev_modules/rptis-255.04.04/server/rptis.conf:/apps/etracs25/modules.conf.d/rptis.conf
