version: "3"

services:
  etracs-server:
    volumes:
      - ./dev_modules/bpls:/services/modules/bpls
      - ./dev_modules/rules:/services/modules/rules
      - ./dev_modules/admin:/services/modules/admin
      - ./dev_modules/rptis/rameses-gov-etracs-rptis-municipality-services.jar:/services/modules/rptis/rameses-gov-etracs-rptis-municipality-services.jar
      - ./dev_modules/rptis/rameses-gov-etracs-rptis-services.jar:/services/modules/rptis/rameses-gov-etracs-rptis-services.jar
