version: "3"

services:

   etracs-server:
      volumes:
         ## this is only a seed mapping, please do not remove
         ## 
         - ../../_custom/.emptydir:/.emptydir

         ## mounted new updates
         ## 
         - ./dev_modules/bpls:/services/modules/bpls

         ## mounted RPTIS from build 255.02.007
         - ./dev_modules/rptis:/services/modules/rptis
