version: "3"

services:

   etracs-server:
      volumes:
         ## this is only a seed mapping, please do not remove
         ## 
         - ../../_custom/.emptydir:/.emptydir

         ## mounted new updates
         ## 
         - ./dev_modules/bpls:/services/modules/bpls

         ## mounted RPTIS - 2.5.02.07.01
         - ./dev_modules/rptis-2.5.02.07.01/server:/services/modules/rptis
         - ./dev_modules/rptis-2.5.02.07.01/rptis.conf:/apps/etracs25/modules.conf.d/rptis.conf
