version: "3"

services:

   etracs-server:
      volumes:
         ## this is only a seed mapping, please do not remove
         ## 
         - ../../_custom/.emptydir:/.emptydir

         ## mounted new updates
         ## 
         - ./dev_modules/bpls:/services/modules/bpls

         ## mounted rptis-255.02.007
         ## 
         - ./dev_modules/rptis-255.02.007/server:/services/modules/rptis
         - ./dev_modules/rptis-255.02.007/server.conf:/apps/etracs25/modules.conf.d/rptis.conf
