version: "3"

services:
  etracs-server:
    volumes:
      ## this is only a seed mapping, please do not remove
      ##
      - ../../_custom/.emptydir:/.emptydir

      ## DEV: to be removed on next build
      ##
      - ./dev_modules/rptis/rameses-gov-etracs-rptis-services.jar:/services/modules/rptis/rameses-gov-etracs-rptis-services.jar
