version: "3"

services:

   etracs-server:
      volumes:
         - ./dev_modules/bpls:/services/modules/bpls
         - ./dev_modules/rules:/services/modules/rules
         - ./dev_modules/admin:/services/modules/admin

         ## mounted RPTIS from build 255.02.007
         - ./dev_modules/rptis:/services/modules/rptis
