version: "3"

services:
  etracs-server:
    container_name: etracs-server
    image: ramesesinc/etracs-server-municipality:2.5.04.03.01
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ./env.conf
      - ../../_res/env.conf
      - ../../_custom/env.conf
    ports:
      - "8060:8060"
      - "8061:8061"
      - "8070:8070"
    volumes:
      - ./modules:/apps/etracs25/modules

      - ../../_custom/datasources:/services/datasources
      - ../../_res/connections:/apps/etracs25/connections/ext
      - ../../_custom/module-server:/apps/etracs25/modules/ext/zzz-lgu-custom-module

      - ../../_custom/output:/apps/server/output
      - ../../_custom/fileserver:/fileserver

      - ./client/reports:/apps/server/templates
      - ../../_custom/module-client/etracs:/apps/server/templates/custom

      ## mounted patch folders
      - ./dev_modules/bpls:/services/modules/bpls
      - ./dev_modules/bpls.conf:/apps/etracs25/modules.conf.d/bpls.conf

      - ./dev_modules/admin:/services/modules/admin
      - ./dev_modules/etracs:/services/modules/etracs
      - ./dev_modules/financial:/services/modules/financial
      - ./dev_modules/jasper:/services/modules/jasper
      - ./dev_modules/rules:/services/modules/rules

      - ./dev_modules/treasury:/services/modules/treasury
      - ./dev_modules/_treasury.conf:/apps/etracs25/modules.conf.d/_treasury.conf

      - ./dev_modules/gdx:/services/modules/gdx
      - ./dev_modules/gdx.conf:/apps/etracs25/modules.conf.d/gdx.conf

      - ./dev_modules/rptis/rameses-gov-etracs-rptis-landtax-report-services.jar:/services/modules/rptis/rameses-gov-etracs-rptis-landtax-report-services.jar
      - ./dev_modules/rptis/rameses-gov-etracs-rptis-landtax-services.jar:/services/modules/rptis/rameses-gov-etracs-rptis-landtax-services.jar
      - ./dev_modules/rptis/rameses-gov-etracs-rptis-report-services.jar:/services/modules/rptis/rameses-gov-etracs-rptis-report-services.jar
      - ./dev_modules/rptis/rameses-gov-etracs-rptis-services.jar:/services/modules/rptis/rameses-gov-etracs-rptis-services.jar
      - ./dev_modules/rptis/rameses-gov-etracs-rptis-sync2-services.jar:/services/modules/rptis/rameses-gov-etracs-rptis-sync2-services.jar

      ## mounted lib
      - ../../_res/lib/osiris2-report.jar:/apps/server/lib/osiris2-report.jar
      - ../../_res/lib/rameses-common2.jar:/apps/server/lib/rameses-common2.jar
