version: "3"

services:

   etracs-server:
      volumes:
         - ./dev_modules/bpls:/services/modules/bpls
         - ./dev_modules/rptis/rameses-gov-etracs-rptis-landtax-services.jar:/services/modules/rptis/rameses-gov-etracs-rptis-landtax-services.jar
