version: "3"

services:
  etracs-server:
    volumes:
      ## this is only a seed mapping, please do not remove
      ##
      - ../../_custom/.emptydir:/.emptydir

      ## DEV MOUNT: to be removed on next build
      ##
      - ./dev_modules/rptis-2.5.04.05.03/rameses-gov-etracs-rptis-services.jar:/services/modules/rptis/rameses-gov-etracs-rptis-services.jar
      - ./dev_modules/rptis-2.5.04.05.03/rameses-gov-etracs-rptis-sync2-services.jar:/services/modules/rptis/rameses-gov-etracs-rptis-sync2-services.jar
