version: "3"

services:

   etracs-server:
      volumes:
         ## this is only a seed mapping, please do not remove
         ## 
         - ../../_custom/.emptydir:/.emptydir

         ## mounted new updates
         ## 
         - ./dev_modules/bpls:/services/modules/bpls

         ## mounted rptis 2.5.04.03.01
         ## 
         - ./dev_modules/rptis-2.5.04.03.01/server:/services/modules/rptis
