version: "3"

services:
  download-node-server:
    volumes:
      ## mounted RPTIS build rptis-255.04.04
      - ../../appserver/etracs/dev_modules/rptis-255.04.04/client:/apps/server/public/resources/downloads/modules/rptis
