version: "3"

services:

   download-node-server:
      volumes:
         ## mounted RPTIS build 255.01.001
         - ../../appserver/etracs/dev_modules/rptis-255.01.001/client:/apps/server/public/resources/downloads/modules/rptis
